routes/web.php
<?php

use App\hotel;
use App\Reservation;
use App\Ville;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

route::group(['middleware' => ['auth','admin']] , function(){

    Route::get('/dashboard', function () {

        $hotels = hotel::get();
        $reservations = Reservation::get();
        $users = User::whereNull('usertype')->get();
        $messages = \App\Contact::get();

        $total = Reservation::count();

        $newreservations = Reservation::where('status','=','Pending')->count();
        $newreservationsperc = $total == 0 ? 0 : $newreservations / $total * 100;

        $acceptedreservations = Reservation::where('status','=','Accepté')->count();
        $acceptedreservationsperc = $total == 0 ? 0 : $acceptedreservations / $total * 100;

        $Refusedreservations = Reservation::where('status','=','Refusé')->count();
        $Refusedreservationsperc = $total == 0 ? 0 : $Refusedreservations / $total * 100;
        return  view('admin.dashboard',compact('hotels','reservations','users','messages','newreservationsperc','acceptedreservationsperc','Refusedreservationsperc','newreservations','acceptedreservations','Refusedreservations'));

    });

    Route::get('/role-register','Admin\DashboardController@registered');
    Route::get('/role-edit/{id}','Admin\DashboardController@registeredit');
    Route::put('/role-register-update/{id} ', 'Admin\DashboardController@registerupdate');
    Route::delete('/role-delete/{id}' , 'Admin\DashboardController@delete')->name('delete');
    Route::get('/avilles' , 'Admin\villeController@index')->name('avilles');
    Route::post('/save-villes' , 'Admin\villeController@store');
    Route::get('/ahotels' , 'Admin\hotelController@index')->name('ahotels');
    Route::post('/save-hotels' , 'Admin\hotelController@store');
    Route::PUT('update-v/', 'Admin\villeController@updatev')->name('updatev');
    Route::get('/villes-update/{id} ', 'Admin\villeController@edit')->name('ville-edit');
    Route::post('/destroyv' , 'Admin\villeController@destroyv')->name('destroyv');
    Route::PUT('update-h/', 'Admin\hotelController@updateh')->name('updateh');
    Route::get('/hotels-update/{id} ', 'Admin\hotelController@edit')->name('hotel-edit');
    Route::post('/destroyh' , 'Admin\hotelController@destroyh')->name('destroyh');
    Route::get('/amaisons' , 'Admin\maisonController@index');
    Route::post('/destroym' , 'Admin\maisonController@destroym')->name('destroym');
    Route::get('/destroym' , 'Admin\maisonController@destroym')->name('destroym');
    Route::get('/acontacts' , 'Admin\contactController@index');
    Route::get('/areservation' , 'Admin\reservationController@index');
    Route::post('changer-status', 'Admin\reservationController@changerstatus')->name('changer-status');

});




route::group(['prefix'=> 'moderateur', ['middleware' => ['auth','moderateur']] ], function(){

    Route::get('/dashboard2', function () {

        $hotels = hotel::where('created_by',Auth::user()->id)->get();

        $myhotels = hotel::where('created_by', Auth::user()->id)->first();
        if ($myhotels) {
            $reservations = Reservation::where('hotel_id', $myhotels->id)->get();
            return view('moderateur.dashboard2',compact('hotels','reservations'));
        }
        return view('moderateur.dashboard2',compact('hotels'));
    });
    Route::get('/hotels' , 'moderateur\hotelController@index');
    Route::post('/enregistrer-hotels' , 'moderateur\hotelController@store');
    Route::PUT('hotels', 'moderateur\hotelController@modifier')->name('modifier');
    Route::get('/hotels-modifier/{id} ', 'moderateur\hotelController@editer')->name('hotel-editer');
    Route::post('/supprimer' , 'moderateur\hotelController@supprimer')->name('supprimer');
    Route::get('/reservation' , 'moderateur\reservationController@index');
    Route::post('change-status', 'moderateur\reservationController@changerstatus2')->name('change-status');

});

Route::get('/mesReservation', function () {
    $reservations = Reservation::where('user_id',Auth::user()->id)->get();
    return view('hotels.mesReservation');
}) ->name('mesReservation') ;


Route::resource('villes', 'VilleController');

Route::resource('hotels', 'HotelController');


Route::resource('maisons', 'MaisonController');
Route::post('/maisons/{id}/store' ,'logementController@store' );
Route::resource('/aboutus', 'AboutusController');
Route::resource('/contacts', 'ContactController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/Reservation', 'reservationController@index')->name('Reservation');
Route::get('hotel/{id}/reservation', 'reservationController@index');
Route::post('/save-reservation' , 'reservationController@reservation');

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $fillable = [
        'user_id' , 'title' , 'message' ,
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/contactController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Contact;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class contactController extends Controller
{
    public function index()
    {
        $contacts = Contact::all();
        return view('admin.contact',compact('contacts'));
    }
}

app/Http/Controllers/contactController.php
<?php

namespace App\Http\Controllers;

use App\Contact;
use App\Ville;
use Illuminate\Http\Request;

class contactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $contacts = Contact::orderby('id', 'desc')->get();
        return view('contacts.contact',compact('contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request , Contact $contact)
    {
        $contact =new Contact() ;
        Contact::create([
            'user_id' => auth()->user()->id ,
            'title' => $request->input('title'),
            'message' => $request->input('message'),
        ]);

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/contacts/contact.blade.php
@extends('layouts.userside')
@section('content')

    <header class="header_area">

        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="left-align-p">
                    <a class="navbar logo_h" href="/home"><img src="{{asset('assets1/image/logo-4.png')}}" alt="Accueil" width="280"></a>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav ml-auto">
                        <li class="nav-item "><a class="nav-link" href="/home">Accueil</a></li>
                        <li class="nav-item"><a class="nav-link" href="/aboutus">à propos</a></li>
                        {{--                    <a href="{{ route('villes.index') }} ">Villes</a>--}}
                        <li class="nav-item"><a class="nav-link" href="{{ route('hotels.index')}}">Hotels</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ route('maisons.index')}}">appartements</a></li>
                        @if (Auth::check())
                            <li class="nav-item"><a class="nav-link" href="{{ route('mesReservation')}}">Mes Reservations</a></li>
                        @endif
                        <li class="nav-item active"><a class="nav-link" href="/contacts">Contact</a></li>
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <section class="breadcrumb_area">
        <div class="overlay bg-parallax" data-stellar-ratio="0.8" data-stellar-vertical-offset="0" data-background=""></div>
        <div class="container">
            <div class="page-cover text-center">
                <h2 class="page-cover-tittle">Contactez nous</h2>
                <ol class="breadcrumb">
                    <li><a href="/home">Home</a></li>
                    <li class="active">Contactez nous</li>
                </ol>
            </div>
        </div>
    </section>
    <!--================Breadcrumb Area =================-->

    <!--================Contact Area =================-->
    <br><br>
{{--    <center><h2 class="mb-30 title_color">Contact</h2></center>--}}
    <center><img src="upload/map.jpg"></center>
    <section class="contact_area section_gap">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="contact_info">
                        <div class="info_item">
                            <i class="lnr lnr-home"></i>
                            <h6>Martil , Maroc</h6>
                            <p>Avenue Martil Rue 5</p>
                        </div>
                        <div class="info_item">
                            <i class="lnr lnr-phone-handset"></i>
                            <h6><a href="#">+2126 23 40 23 39</a></h6>
                            <p>Applez nous !<p>
                        </div>
                        <div class="info_item">
                            <i class="lnr lnr-envelope"></i>
                            <h6><a href="#">Firdaouskb@gmail.com</a></h6>
                            <p>Vous pouvez nous envoyez des messages!!</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-9">
                    <form class="row contact_form" action="{{ route('contacts.store') }}" method="POST" id="contactForm" novalidate="novalidate">
                        @csrf
                        {{ csrf_field() }}
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" class="form-control" id="name" name="title" placeholder="Sujet de votre message">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <textarea class="form-control" name="message" id="message" rows="1" placeholder="Votre message..."></textarea>
                            </div>
                        </div>
                        <div class="col-md-12 text-right">
                            <button type="submit" class="btn theme_btn button_hover">Envoyer</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>




@endsection