routes/web.php
<?php

use App\hotel;
use App\Reservation;
use App\Ville;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

route::group(['middleware' => ['auth','admin']] , function(){

    Route::get('/dashboard', function () {

        $hotels = hotel::get();
        $reservations = Reservation::get();
        $users = User::whereNull('usertype')->get();
        $messages = \App\Contact::get();

        $total = Reservation::count();

        $newreservations = Reservation::where('status','=','Pending')->count();
        $newreservationsperc = $total == 0 ? 0 : $newreservations / $total * 100;

        $acceptedreservations = Reservation::where('status','=','Accepté')->count();
        $acceptedreservationsperc = $total == 0 ? 0 : $acceptedreservations / $total * 100;

        $Refusedreservations = Reservation::where('status','=','Refusé')->count();
        $Refusedreservationsperc = $total == 0 ? 0 : $Refusedreservations / $total * 100;
        return  view('admin.dashboard',compact('hotels','reservations','users','messages','newreservationsperc','acceptedreservationsperc','Refusedreservationsperc','newreservations','acceptedreservations','Refusedreservations'));

    });

    Route::get('/role-register','Admin\DashboardController@registered');
    Route::get('/role-edit/{id}','Admin\DashboardController@registeredit');
    Route::put('/role-register-update/{id} ', 'Admin\DashboardController@registerupdate');
    Route::delete('/role-delete/{id}' , 'Admin\DashboardController@delete')->name('delete');
    Route::get('/avilles' , 'Admin\villeController@index')->name('avilles');
    Route::post('/save-villes' , 'Admin\villeController@store');
    Route::get('/ahotels' , 'Admin\hotelController@index')->name('ahotels');
    Route::post('/save-hotels' , 'Admin\hotelController@store');
    Route::PUT('update-v/', 'Admin\villeController@updatev')->name('updatev');
    Route::get('/villes-update/{id} ', 'Admin\villeController@edit')->name('ville-edit');
    Route::post('/destroyv' , 'Admin\villeController@destroyv')->name('destroyv');
    Route::PUT('update-h/', 'Admin\hotelController@updateh')->name('updateh');
    Route::get('/hotels-update/{id} ', 'Admin\hotelController@edit')->name('hotel-edit');
    Route::post('/destroyh' , 'Admin\hotelController@destroyh')->name('destroyh');
    Route::get('/amaisons' , 'Admin\maisonController@index');
    Route::post('/destroym' , 'Admin\maisonController@destroym')->name('destroym');
    Route::get('/destroym' , 'Admin\maisonController@destroym')->name('destroym');
    Route::get('/acontacts' , 'Admin\contactController@index');
    Route::get('/areservation' , 'Admin\reservationController@index');
    Route::post('changer-status', 'Admin\reservationController@changerstatus')->name('changer-status');

});




route::group(['prefix'=> 'moderateur', ['middleware' => ['auth','moderateur']] ], function(){

    Route::get('/dashboard2', function () {

        $hotels = hotel::where('created_by',Auth::user()->id)->get();

        $myhotels = hotel::where('created_by', Auth::user()->id)->first();
        if ($myhotels) {
            $reservations = Reservation::where('hotel_id', $myhotels->id)->get();
            return view('moderateur.dashboard2',compact('hotels','reservations'));
        }
        return view('moderateur.dashboard2',compact('hotels'));
    });
    Route::get('/hotels' , 'moderateur\hotelController@index');
    Route::post('/enregistrer-hotels' , 'moderateur\hotelController@store');
    Route::PUT('hotels', 'moderateur\hotelController@modifier')->name('modifier');
    Route::get('/hotels-modifier/{id} ', 'moderateur\hotelController@editer')->name('hotel-editer');
    Route::post('/supprimer' , 'moderateur\hotelController@supprimer')->name('supprimer');
    Route::get('/reservation' , 'moderateur\reservationController@index');
    Route::post('change-status', 'moderateur\reservationController@changerstatus2')->name('change-status');

});

Route::get('/mesReservation', function () {
    $reservations = Reservation::where('user_id',Auth::user()->id)->get();
    return view('hotels.mesReservation');
}) ->name('mesReservation') ;


Route::resource('villes', 'VilleController');

Route::resource('hotels', 'HotelController');


Route::resource('maisons', 'MaisonController');
Route::post('/maisons/{id}/store' ,'logementController@store' );
Route::resource('/aboutus', 'AboutusController');
Route::resource('/contacts', 'ContactController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/Reservation', 'reservationController@index')->name('Reservation');
Route::get('hotel/{id}/reservation', 'reservationController@index');
Route::post('/save-reservation' , 'reservationController@reservation');

app/Maison.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Maison extends Model
{
    protected $fillable = [
    'nombre_de_chambre',  'ville_id' ,  'surface', 'prix', 'chauffage', 'climatisation', 'content', 'image'];

    public function ville(){
        return $this->belongsTo("App\Ville" , 'ville_id');
    }
    public function logements(){
        return $this->hasMany(Logement::class);
    }
    public function users()
    {
        return $this->belongsToMany('App\User');
    }
}

app/Http/Controllers/Admin/maisonController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Maison;
use Illuminate\Http\Request;

class maisonController extends Controller
{
    public function index()
    {
        $maisons = Maison::all();
        return view('admin.amaison',compact('maisons'));

    }
    public function destroym(Request $r)
    {
        $maison = Maison::findOrfail($r->id);

        $maison->delete();

        toast('Maison ajouté !','success');

        return redirect('/amaisons');
    }
}

app/Http/Controllers/maisonController.php
<?php

namespace App\Http\Controllers;

use App\Maison;
use App\Ville;
use Illuminate\Http\Request;


class maisonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $villes = Ville::all();
        $maisons = Maison::orderby('id', 'desc')->get();
        return view('maisons.index',compact('maisons','villes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $villes = Ville::skip(1)->take(3)->get();
        return view('maisons.create',compact('villes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
              //  'user_id' => 'required',
                'ville_id' => 'required',
                'nombre_de_chambre' => 'required',
                'prix' => 'required',
                'surface' => 'required',
                'chauffage' => 'required',
                'climatisation' => 'required',
                'content' => 'required',
                'image' => 'required|image|mimes:jpeg,jpg,png|max:1000'
        ]);
        $destinationPath = public_path('upload');
        $image = $request->file('image');
        $input['imagename'] = time() . '.' . $image->getClientOriginalExtension();
        $image->move($destinationPath, $input['imagename']);
        $dbPath = $destinationPath . "/" . $input['imagename'];
        $maison = new Maison();
        $maison->user_id = auth()->user()->id;
        $maison->nombre_de_chambre = $request->input('nombre_de_chambre');
        $maison->prix = $request->input('prix');
        $maison->surface = $request->input('surface');
        $maison->chauffage = $request->input('chauffage');
        $maison->climatisation = $request->input('climatisation');
        $maison->content = $request->input('content');
        $maison->ville_id = $request->input('ville_id');
        $maison->prix = $request->input('prix');
        $maison->image = $input['imagename'];
        $maison->save();
        return redirect()->route('maisons.index')->with('success', 'maison created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Maison $maison)
    {
        $villes = Ville::all();
        return view('maisons.show',compact('maison','villes'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Maison $maison)
    {
        $villes = Ville::skip(1)->take(3)->get();

        return view('maisons.edit',compact('maison','villes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Maison $maison)
    {
        $request->validate([

        ]);
        $maison->update($request->all());
        return redirect()->route('maisons.index')
            ->with('success','maison modifié avec succès');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Maison $maison)
    {
        $maison->delete();
        return redirect()->route('maisons.index')
            ->with('success','maison supprimée avec succès');
    }
}

resources/views/maisons/create.blade.php
    @extends('layouts.userside')


    @section('content')


        <header class="header_area">

            <div class="container">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="left-align-p">
                        <a class="navbar logo_h" href="/home"><img src="{{asset('assets1/image/logo-4.png')}}" alt="Accueil" width="280"></a>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                        <ul class="nav navbar-nav menu_nav ml-auto">
                            <li class="nav-item "><a class="nav-link" href="/home">Accueil</a></li>
                            <li class="nav-item"><a class="nav-link" href="/aboutus">à propos</a></li>
                            {{--                    <a href="{{ route('villes.index') }} ">Villes</a>--}}
                            <li class="nav-item"><a class="nav-link" href="{{ route('hotels.index')}}">Hotels</a></li>
                            <li class="nav-item active"><a class="nav-link" href="{{ route('maisons.index')}}">appartements</a></li>
                            @if (Auth::check())
                                <li class="nav-item"><a class="nav-link" href="{{ route('mesReservation')}}">Mes Reservations</a></li>
                            @endif
                            <li class="nav-item"><a class="nav-link" href="/contacts">Contact</a></li>
                            @guest
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                                @if (Route::has('register'))
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                    </li>
                                @endif
                            @else
                                <li class="nav-item dropdown">
                                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                        {{ Auth::user()->name }} <span class="caret"></span>
                                    </a>

                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{{ route('logout') }}"
                                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            {{ __('Logout') }}
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            @csrf
                                        </form>
                                    </div>
                                </li>
                            @endguest
                        </ul>
                    </div>
                </nav>
            </div>
        </header>

        <section class="breadcrumb_area blog_banner_alo">
            <div class="overlay bg-parallax" data-stellar-ratio="0.8" data-stellar-vertical-offset="0" data-background="">

            </div>
            <div class="container">
                <div class="page-cover text-center">
                    <h2 class="page-cover-tittle f_48">Ajouter un Nouvel Appartement</h2>
                    <ol class="breadcrumb">
                        <li><a href="{{ route('maisons.index') }}">Les Appartements</a></li>
                        <li><a href="{{ route('maisons.create') }}">Ajouter</a></li>
                    </ol>
                </div>
            </div>
        </section>
        <br/>
        <div class="pull-left">
            <a class="genric-btn warning circle" href="{{ route('maisons.index') }}"> retour </a>
        </div>
        <center>
            <h2 class="mb-30 title_color">Ajouter </h2>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form action="{{ route('maisons.store') }}" method="POST" enctype="multipart/form-data" >
                @csrf
                <div class="mt-10">
                    <div class="col-md-6">
                        <div class="text-left">
                            <label>Image</label>
                        </div>
                        <input type="file" name="image" class="form-control" method="post" enctype="multipart/form-data"  placeholder="image">

                        <div class="text-left">
                            <label>Ville</label>
                        </div>
                        <div class="form-select" id="default-select">
                            <select name="ville_id" class="form-control">
                                @php
                                    $villes = \App\Ville::all();
                                @endphp
                                @foreach($villes as $ville)
                                    <option value="{{ $ville->id }}">{{ $ville->name }}</option>
                                @endforeach
                            </select>
                        </div>


                        <br/>
                        <div class="text-left">
                            <label>Nombre de chambres</label>
                        </div>
                        <div class="form-group">

                            <input type="text" class="form-control" id="name" name="nombre_de_chambre" value="" placeholder="Nombre">
                        </div>
                        <div class="text-left">
                            <label>Surface</label>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="email" name="surface"  value="" placeholder="Surface">
                        </div>
                        <div class="text-left">
                            <label>Prix</label>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="email" placeholder="Prix" name="prix" value="" >
                        </div>
                        <div class="text-left">
                            <label>Chauffage</label>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="email"placeholder="Chauffage" name="chauffage" value="">
                        </div>
                        <div class="text-left">
                            <label>Climatisation:</label>
                        </div>

                        <div class="form-group">
                            <input type="text" class="form-control" id="email" placeholder="Climatisation" name="climatisation" value="">
                        </div>
                        <div class="text-left">
                            <label>Content:</label>
                        </div>

                        <div class="form-group">
                            <input type="text" class="form-control" id="email"placeholder="Decription" name="content" value="">
                        </div>
                    </div>
                </div>
                <button type="submit" class="genric-btn warning circle">
                    Ajouter
                </button>

            </form>
            <br/>

        </center>





@endsection

resources/views/maisons/edit.blade.php
@extends('layouts.userside')
@section('content')

{{--<center>--}}
{{--    <div id="right-side" class="col-md-8">--}}
{{--        <div class="card bg-secondary text-light" >--}}
{{--            <div class="card-header">--}}
{{--                <h3 class="card-title text-center"> Modifier </h3>--}}
{{--            </div>--}}
{{--            <div class="card-body">--}}
{{--                <form action="{{ route('maisons.update',$maison->id) }}"  class="contact-form"  method="POST" enctype="multipart/form-data" >--}}
{{--                    @csrf--}}
{{--                    @method('PUT')--}}
{{--                    <strong>Image:</strong>--}}
{{--                    <input type="file" name="image" class="form-control" enctype="multipart/form-data"  placeholder="image"  />--}}
{{--                    <img  src="{{ asset("uploads").\Illuminate\Support\Str::substr($maison->image,35)  }}" class="img-thumbnail" alt="" width="80px"/>--}}
{{--                    <div class="form-group">--}}
{{--                        <strong>ville:</strong>--}}
{{--                        <select name="ville_id" class="form-control">--}}
{{--                            @php--}}
{{--                                $villes = \App\Ville::all();--}}
{{--                            @endphp--}}
{{--                            @foreach($villes as $ville)--}}
{{--                                <option value="{{ $ville->id }}">{{ $ville->name }}</option>--}}
{{--                            @endforeach--}}
{{--                        </select>--}}
{{--                    </div>--}}
{{--                    <div class="form-group">--}}
{{--                        <strong>nombre_de_chambre:</strong>--}}
{{--                        <input type="text" name="nombre_de_chambre" value="{{$maison->nombre_de_chambre}}"  class="form-control m-1 text-center" >--}}
{{--                    </div>--}}
{{--                    <div class="form-group">--}}
{{--                        <strong>surface:</strong>--}}
{{--                        <input type="text" name="surface" value="{{$maison->surface}}"  class="form-control m-1 text-center" >--}}
{{--                    </div>--}}
{{--                    <div class="form-group">--}}
{{--                        <strong>prix:</strong>--}}
{{--                        <input type="text" name="prix" value="{{$maison->prix}}"  class="form-control m-1 text-center"  >--}}
{{--                    </div>--}}
{{--                    <div class="form-group">--}}
{{--                        <strong>chauffage:</strong>--}}
{{--                        <input type="text" name="chauffage" value="{{$maison->chauffage}}"  class="form-control m-1 text-center">--}}
{{--                    </div>--}}
{{--                    <div class="form-group">--}}
{{--                        <strong>climatisation:</strong>--}}
{{--                        <input type="text" name="climatisation" value="{{$maison->climatisation}}" class="form-control m-1 text-center"  >--}}
{{--                    </div>--}}
{{--                    <div class="form-group">--}}
{{--                        <strong>content:</strong>--}}
{{--                        <input type="text" name="content" value="{{$maison->content}}" class="form-control m-1 text-center" >--}}
{{--                    </div>--}}
{{--                    <br/>--}}
{{--                    <button type="submit" class="btn bg-info btn-block text-light m-1"> Edit </button>--}}
{{--                </form>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}
{{--</center>--}}
<header class="header_area">

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="left-align-p">
                <a class="navbar logo_h" href="/home"><img src="{{asset('assets1/image/logo-4.png')}}" alt="Accueil" width="280"></a>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                <ul class="nav navbar-nav menu_nav ml-auto">
                    <li class="nav-item "><a class="nav-link" href="/home">Accueil</a></li>
                    <li class="nav-item"><a class="nav-link" href="/aboutus">à propos</a></li>
                    {{--                    <a href="{{ route('villes.index') }} ">Villes</a>--}}
                    <li class="nav-item"><a class="nav-link" href="{{ route('hotels.index')}}">Hotels</a></li>
                    <li class="nav-item active"><a class="nav-link" href="{{ route('maisons.index')}}">appartements</a></li>
                    @if (Auth::check())
                        <li class="nav-item"><a class="nav-link" href="{{ route('mesReservation')}}">Mes Reservations</a></li>
                    @endif
                    <li class="nav-item"><a class="nav-link" href="/contacts">Contact</a></li>
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </nav>
    </div>
</header>

<section class="breadcrumb_area blog_banner_alo">
    <div class="overlay bg-parallax" data-stellar-ratio="0.8" data-stellar-vertical-offset="0" data-background="">

    </div>
    <div class="container">
        <div class="page-cover text-center">
            <h2 class="page-cover-tittle f_48">Modifier</h2>
            <ol class="breadcrumb">
                <li><a href="{{ route('maisons.index') }}">Les Appartements</a></li>
                <li><a href="">Modifier</a></li>
            </ol>
        </div>
    </div>
</section>
<br/>
<br/><br/><br/><br/>
<center>
            <div class="pull-left">
                <a class="genric-btn warning circle" href="{{ route('maisons.index') }}"> retour </a>
            </div>
            <h2 class="mb-30 title_color">Modifier Votre Appartement</h2>
            <form action="{{ route('maisons.update',$maison->id) }}"  class="contact-form"  method="POST" enctype="multipart/form-data" >
                @csrf
                @method('PUT')
                <div class="mt-10">
                    <div class="col-md-6">
                        <div class="text-left">
                            <label>Image</label>
                        </div>
                        <input type="file" name="image" class="form-control" enctype="multipart/form-data"  placeholder="image"  />
                        <img  src="{{ asset("uploads").\Illuminate\Support\Str::substr($maison->image,35)  }}" class="img-thumbnail" alt="" width="80px"/>

                        <div class="text-left">
                            <label>Ville</label>
                        </div>
                        <div class="form-select" id="default-select">
                            <select name="ville_id" class="form-control" style="display: block;">
                                @php
                                    $villes = \App\Ville::all();
                                @endphp
                                @foreach($villes as $ville)
                                    <option value="{{ $ville->id }}">{{ $ville->name }}</option>
                                @endforeach
                            </select>
                        </div>


                        <br/>
                        <div class="text-left">
                            <label>Nombre de chambres</label>
                        </div>
                        <div class="form-group">

                            <input type="text" class="form-control" id="name" name="nombre_de_chambre" value="{{$maison->nombre_de_chambre}}" placeholder="Enter your name">
                        </div>
                        <div class="text-left">
                            <label>Surface</label>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="email" name="surface" value="{{$maison->surface}}">
                        </div>
                        <div class="text-left">
                            <label>Prix</label>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="email" name="prix" value="{{$maison->prix}}" >
                        </div>
                        <div class="text-left">
                            <label>Chauffage</label>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="email" name="chauffage" value="{{$maison->chauffage}}">
                        </div>
                        <div class="text-left">
                            <label>climatisation:</label>
                        </div>

                        <div class="form-group">
                            <input type="text" class="form-control" id="email" name="climatisation" value="{{$maison->climatisation}}">
                        </div>
                        <div class="text-left">
                            <label>content:</label>
                        </div>

                        <div class="form-group">
                            <input type="text" class="form-control" id="email" name="content" value="{{$maison->content}}">
                        </div>
                    </div>
                </div>
                <button class="genric-btn warning circle">
                    Update
                </button>

            </form>
    <br/>

</center>



</div>

@endsection